source :rubygems
gem 'mixlib-cli', :require => 'mixlib/cli'
gem 'mixlib-log', :require => 'mixlib/log'
gem 'json'
gem 'eventmachine'
gem 'em-websocket'
gem 'em-dir-watcher'
gem 'rb-inotify'
gem 'nagios_analyzer'
gem 'thin', '1.2.8'
gem 'async_sinatra', :require => 'sinatra/async'
gem 'haml'
gem 'chef', '0.9.14'
gem 'spice', :git => 'git://github.com/portertech/spice.git'
